name: first-workflow
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install
    - name: Lint test
      run: npm run lint
    - name: Build
      run: npm run build
    - name: Test
      run: npm run test
    - name: Deploy
      run: echo "deploying.."