name: check issues and print event metadata
on: 
  issues:
    types: [opened, edited, deleted]
jobs:
  checking:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Print event metadata
      run: echo "event metadata: ${{ toJson(github.event) }}"